# Generated by Django 5.0.1 on 2024-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
