# Generated by Django 5.0.1 on 2024-03-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_waitinglist_email'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='content_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.class'),
        ),
    ]
