# Generated by Django 5.0.1 on 2024-03-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_quiz_content_id_alter_quiz_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quiz_questions', to='lessons.quizquestion'),
        ),
    ]
