# Generated by Django 5.0.3 on 2024-03-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_quizquestion_weight_quizresponse_delete_quizprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='responses',
            field=models.ManyToManyField(related_name='responses', to='lessons.quizquestion'),
        ),
    ]
