# Generated by Django 5.0.3 on 2024-03-15 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_quizresponse_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresponse',
            unique_together={('quiz', 'question', 'student')},
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='responses',
        ),
    ]
