# Generated by Django 5.0.3 on 2024-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_quizresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='responses',
            field=models.ManyToManyField(related_name='question_responses', to='lessons.quizresponse'),
        ),
    ]
